# Configuration du projet
vector_store:
  db_dir: "./chroma_db"

embeddings:
  model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  device: "cpu"

document_loader:
  data_dir: "./data"
  supported_extensions: [".pdf"]

chunking:
  chunk_size: 2500
  chunk_overlap: 500
  separators: ["\n\n", "\n", " ", ""]

retriever:
  search_type: "similarity"
  search_kwargs:
    k: 7  
    score_threshold: 0.2

llm:
  model_name: "distilbert/distilgpt2"  
  model_kwargs:
    temperature: 0.1
    max_new_tokens: 256  
    repetition_penalty: 1.1

openai:
  api_key: "" 
  model_name: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 512
